name: Markdown and Jupyter Notebook Link Checker
description: Validate links in Markdown files and Jupyter Notebooks
author: mr8lu
branding:
  icon: 'link'
  color: 'blue'
inputs:
  PAT_TOKEN:
    description: 'GitHub PAT for authentication'
    required: false
  directory:
    description: 'The directory to search for markdown and notebook files'
    required: true
    default: '.'
outputs:
  broken_links_found:
    description: 'Indicates if any broken links were found'
runs:
  using: 'composite'
  steps:
    - name: Checkout script repository
      uses: actions/checkout@v3
      with:
        repository: mr8lu/link-validator
        path: .github/workflows/script
    - name: Set up python
      shell: bash
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r .github/workflows/script/requirements.txt
        # pip install beautifulsoup4==4.12.3 nbformat==5.10.4 requests==2.32.2

    - name: Run Link Checker
      shell: bash
      env:
        PAT_TOKEN: ${{ inputs.PAT_TOKEN }}
        directory: ${{ inputs.directory }}
      run: |
        source venv/bin/activate
        python .github/workflows/script/check_links.py
